apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: nfs
bases:
  - ./deploy
resources:
  - namespace.yml
  - storage.yml
patchesStrategicMerge:
  - patch_nfs_details.yml
