apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
  namespace: nfs
spec:
  template:
    spec:
      containers:
        - name: nfs-client-data-provisioner
          env:
            - name: NFS_SERVER
              value: 127.0.0.1
            - name: NFS_PATH
              value: /data/
        - name: nfs-client-tmp-provisioner
          env:
            - name: NFS_SERVER
              value: 127.0.0.1
            - name: NFS_PATH
              value: /tmp/
        - name: nfs-client-storage-provisioner
          env:
            - name: NFS_SERVER
              value: 127.0.0.1
            - name: NFS_PATH
              value: /storage/
      volumes:
        - name: nfs-client-data-root
          nfs:
            server: 127.0.0.1
            path: /data/
        - name: nfs-client-tmp-root
          nfs:
            server: 127.0.0.1
            path: /tmp/
        - name: nfs-client-storage-root
          nfs:
            server: 127.0.0.1
            path: /storage/
