apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
  namespace: nfs
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 127.0.0.1
            - name: NFS_PATH
              value: /data/
      volumes:
        - name: nfs-client-root
          nfs:
            server: 127.0.0.1
            path: /data/
