apiVersion: batch/v1
kind: Job
metadata:
  name: job-build-backend
  labels:
    app: backend
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: build-backend
          image: localhost:5000/hms:latest
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              cd /export &&
              npm install --verbose &&
              npm run backend:build &&
              go get -d -v ./... &&
              go install -v ./... &&
              go mod vendor &&
              go build -ldflags="-s -w" -mod=vendor -o ./dist/api ./cmd/api/main.go &&
              go build -ldflags="-s -w" -mod=vendor -o ./dist/downloader ./cmd/downloader/main.go &&
              go build -ldflags="-s -w" -mod=vendor -o ./dist/encoder ./cmd/encoder/main.go &&
              go build -ldflags="-s -w" -mod=vendor -o ./dist/file ./cmd/file/main.go;
          volumeMounts:
            - name: pvc-dist-build
              mountPath: /export/dist/
            - name: pvc-backend-build
              mountPath: /export/backend/
            - name: pvc-sys-build
              mountPath: /export/sys/
            - name: pvc-cmd-build
              mountPath: /export/cmd/
      volumes:
        - name: pvc-dist-build
          persistentVolumeClaim:
            claimName: pvc-dist-build
        - name: pvc-backend-build
          persistentVolumeClaim:
            claimName: pvc-backend-build
        - name: pvc-sys-build
          persistentVolumeClaim:
            claimName: pvc-sys-build
        - name: pvc-cmd-build
          persistentVolumeClaim:
            claimName: pvc-cmd-build
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-build-frontend
  labels:
    app: frontend
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      initContainers:
        - name: wait-for-backend
          image: bitnami/kubectl:latest
          command:
            - "/bin/sh"
            - "-c"
          # curl --head -s --max-time 21600 -o /dev/null -w "%{http_code}" "http://backend.hms.svc.cluster.local:4100/ping"
          args:
            - |
              while [[ $(kubectl -n hms get pods --selector=app=backend -o jsonpath='{.items[*].status.containerStatuses[*].started}') -ne 1 ]]; do
                echo "Waiting backend to response..."
                sleep 5
              done
      containers:
        - name: build-frontend
          image: localhost:5000/hms:latest
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              cd /export &&
              npm install --verbose &&
              npm run client:build
          volumeMounts:
            - name: pvc-dist-build
              mountPath: /export/dist/
            - name: pvc-src-build
              mountPath: /export/src/
      volumes:
        - name: pvc-dist-build
          persistentVolumeClaim:
            claimName: pvc-dist-build
        - name: pvc-src-build
          persistentVolumeClaim:
            claimName: pvc-src-build
      restartPolicy: Never
