apiVersion: batch/v1
kind: Job
metadata:
  name: job-build-backend
  labels:
    app: backend
spec:
  # ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: build-backend
          image: localhost:5000/hms:latest
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              cd /export &&
              if [ ! -d /export/dist/backend/ ]; then { [[ ! -d /export/node_modules/ ]] && npm install --verbose; npm run backend:build; }; fi &&
              if [ ! -f /export/dist/api ] || [ ! -f /export/dist/downloader ] || [ ! -f /export/dist/encoder ] || [ ! -f /export/dist/file ]; then { go get -d -v ./... && go install -v ./... && go mod vendor; }; fi &&
              [[ ! -f /export/dist/api ]] && go build -ldflags="-s -w" -mod=vendor -o /export/dist/api /export/cmd/api/main.go &&
              [[ ! -f /export/dist/downloader ]] && go build -ldflags="-s -w" -mod=vendor -o /export/dist/downloader /export/cmd/downloader/main.go &&
              [[ ! -f /export/dist/encoder ]] && go build -ldflags="-s -w" -mod=vendor -o /export/dist/encoder /export/cmd/encoder/main.go &&
              [[ ! -f /export/dist/file ]] && go build -ldflags="-s -w" -mod=vendor -o /export/dist/file /export/cmd/file/main.go;
          volumeMounts:
            - name: pvc-dist-backend-build
              mountPath: /export/dist/
            - name: pvc-backend-build
              mountPath: /export/backend/
            - name: pvc-sys-build
              mountPath: /export/sys/
            - name: pvc-cmd-build
              mountPath: /export/cmd/
      volumes:
        - name: pvc-dist-backend-build
          persistentVolumeClaim:
            claimName: pvc-dist-backend-build
        - name: pvc-backend-build
          persistentVolumeClaim:
            claimName: pvc-backend-build
        - name: pvc-sys-build
          persistentVolumeClaim:
            claimName: pvc-sys-build
        - name: pvc-cmd-build
          persistentVolumeClaim:
            claimName: pvc-cmd-build
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-build-frontend
  labels:
    app: frontend
spec:
  # ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: build-frontend
          image: localhost:5000/hms:latest
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              while [[ $(curl --head -s --max-time 10 -o /dev/null -w "%{http_code}" "http://backend.hms:4100/ping") -ne 200 ]]; do { echo "Waiting backend to response..."; sleep 5; } done &&
              cd /export &&
              echo "building frontend ..." &&
              if [ ! -d /export/dist/client/ ]; then { [[ ! -d /export/node_modules/ ]] && npm install --verbose; npm run client:build; }; fi;
          volumeMounts:
            - name: pvc-dist-frontend-build
              mountPath: /export/dist/
            - name: pvc-src-build
              mountPath: /export/src/
      volumes:
        - name: pvc-dist-frontend-build
          persistentVolumeClaim:
            claimName: pvc-dist-frontend-build
        - name: pvc-src-build
          persistentVolumeClaim:
            claimName: pvc-src-build
