apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dist
  labels:
    dirname: dist
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: data-repo
  nfs:
    server: 127.0.0.1
    path: /data/dist/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
  labels:
    dirname: db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: data-repo
  nfs:
    server: 127.0.0.1
    path: /data/db/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tmp
  labels:
    dirname: tmp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: tmp-repo
  nfs:
    server: 127.0.0.1
    path: /tmp/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
  labels:
    dirname: storage
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 127.0.0.1
    path: /storage/
