apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dist
  labels:
    dirname: dist
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 127.0.0.1
    path: /data/dist/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
  labels:
    dirname: db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 127.0.0.1
    path: /data/db/
