apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dist-backend
  labels:
    dirname: dist-backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 127.0.0.1
    path: /data/dist/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dist-frontend
  labels:
    dirname: dist-frontend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 127.0.0.1
    path: /data/dist/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-backend
  labels:
    dirname: db-backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 127.0.0.1
    path: /data/db/
