apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dist-backend-build
  labels:
    dirname: dist-backend-build
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /data/dist/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dist-frontend-build
  labels:
    dirname: dist-frontend-build
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /data/dist/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend-build
  labels:
    dirname: backend-build
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /web/repos/home-media/backend/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-src-build
  labels:
    dirname: src-build
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /web/repos/home-media/src/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sys-build
  labels:
    dirname: sys-build
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /web/repos/home-media/sys/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cmd-build
  labels:
    dirname: cmd-build
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /web/repos/home-media/cmd/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dist-backend
  labels:
    dirname: dist-backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /data/dist/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dist-frontend
  labels:
    dirname: dist-frontend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /data/dist/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-backend
  labels:
    dirname: db-backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /data/db/
