apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dist-build
spec:
  storageClassName: storage-repo
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      dirname: dist-build
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dist-backend
spec:
  storageClassName: storage-repo
  accessModes:
    - ReadOnlyMany
  selector:
    matchLabels:
      dirname: dist-backend
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backend-build
spec:
  storageClassName: storage-repo
  accessModes:
    - ReadOnlyMany
  selector:
    matchLabels:
      dirname: backend-build
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-src-build
spec:
  storageClassName: storage-repo
  accessModes:
    - ReadOnlyMany
  selector:
    matchLabels:
      dirname: src-build
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sys-build
spec:
  storageClassName: storage-repo
  accessModes:
    - ReadOnlyMany
  selector:
    matchLabels:
      dirname: sys-build
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cmd-build
spec:
  storageClassName: storage-repo
  accessModes:
    - ReadOnlyMany
  selector:
    matchLabels:
      dirname: cmd-build
  resources:
    requests:
      storage: 10Gi
