---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dist-backend
  namespace: hms
spec:
  storageClassName: storage-repo
  accessModes:
    - ReadOnlyMany
  selector:
    matchLabels:
      dirname: dist-backend
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-backend
  namespace: hms
spec:
  storageClassName: storage-repo
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      dirname: db-backend
  resources:
    requests:
      storage: 10Gi
