---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dist
  namespace: hms
spec:
  storageClassName: data-repo
  accessModes:
    - ReadOnlyMany
  selector:
    matchLabels:
      dirname: dist
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  namespace: hms
spec:
  storageClassName: data-repo
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      dirname: db
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
  namespace: hms
spec:
  storageClassName: data-repo
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      dirname: storage
  resources:
    requests:
      storage: 1000Gi
