kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: hms
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4100
  - name: internal
    protocol: TCP
    port: 4100
    targetPort: 4100
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: hms
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4000
  - name: internal
    protocol: TCP
    port: 4000
    targetPort: 4000
  - name: serve
    protocol: TCP
    port: 4200
    targetPort: 4200
---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: hms
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4110
  - name: internal
    protocol: TCP
    port: 4110
    targetPort: 4110
---
kind: Service
apiVersion: v1
metadata:
  name: file
  namespace: hms
  labels:
    app: file
spec:
  type: ClusterIP
  selector:
    app: file
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4150
  - name: internal
    protocol: TCP
    port: 4150
    targetPort: 4150
