version: "3.9"

services:
  app:
    image: docker.elastic.co/logstash/logstash:8.4.2
    ports:
      - 5000:5000
      - 9600:9600
    environment:
      - LS_JAVA_OPTS=-Xmx2048m -Xms2048m
      - XPACK_MONITORING_ENABLED=false
      - HTTP_HOST=0.0.0.0
    networks:
      - backend
    volumes:
      - pipeline:/usr/share/logstash/pipeline/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager

networks:
  backend:
    driver: overlay
    attachable: true

volumes:
  pipeline:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=${NFS_SERVER_ADDR},nfsvers=4,exec,nodev,noatime,nodiratime,soft,rsize=1048576,wsize=1048576'
      device: ':/web/repos/home-media/channel/'
