apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-channel
  labels:
    dirname: channel
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 192.168.56.55
    path: /web/repos/home-media/channel/
