apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-channel
  labels:
    dirname: channel
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-repo
  nfs:
    server: 127.0.0.1
    path: /data/dist/channel/
